# Generated by Django 3.1.2 on 2020-10-25 21:10

import ATLAS.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ATLAS', '0002_auto_20201025_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestatlas_user',
            name='requester',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestatlas_user',
            name='file',
            field=models.FileField(help_text='Load compressed .nii file (Lead-DBS format)', upload_to=ATLAS.models.user_directory_path_req),
        ),
        migrations.AlterField(
            model_name='requestatlas_user',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', help_text='Logo ATLAS', upload_to='requests/image'),
        ),
    ]
