# Generated by Django 3.1.2 on 2020-10-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATLAS', '0003_auto_20201025_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestatlas_user',
            name='version',
            field=models.CharField(default='v.1.0', help_text='Version: v. X.x', max_length=50, verbose_name='Version ATLAS'),
        ),
    ]
