# Generated by Django 3.1.2 on 2020-10-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATLAS', '0004_auto_20201026_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlas_properties',
            name='laterality',
            field=models.CharField(blank=True, choices=[('lh', 'LeftHemisphere'), ('rh', 'Right Hemisphere'), ('bh', 'Both Hemispheres'), ('mh', 'Mixed'), ('ml', 'Midline')], default='bh', help_text='Which side?', max_length=2, verbose_name='Side'),
        ),
        migrations.AlterField(
            model_name='requestatlas_user',
            name='laterality',
            field=models.CharField(blank=True, choices=[('lh', 'LeftHemisphere'), ('rh', 'Right Hemisphere'), ('bh', 'Both Hemispheres'), ('mh', 'Mixed'), ('ml', 'Midline')], default='bh', help_text='Which side?', max_length=2, verbose_name='Side'),
        ),
    ]
